/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.io.PrintWriter;
import java.awt.*;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.sql.SQLException;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Brambilla de Mello
 */
public class Home extends javax.swing.JFrame {

    /**
     *
     */
    public int UserID;

    /**
     * Creates new form Home
     */
    public Home() {

        initComponents();
    //    setIcon();
        testConnection();
        text_area.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grup_gender = new javax.swing.ButtonGroup();
        pnl_bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        txt_pwd = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lb_pwdLogin = new javax.swing.JLabel();
        lb_userLogin = new javax.swing.JLabel();
        lb_iconLogin = new javax.swing.JLabel();
        lb_signUp = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        lb_connection_login = new javax.swing.JLabel();
        back_Log = new javax.swing.JLabel();
        signUp = new javax.swing.JPanel();
        txt_fName = new javax.swing.JTextField();
        sep_fName = new javax.swing.JSeparator();
        lb_Reg = new javax.swing.JLabel();
        sep_lName = new javax.swing.JSeparator();
        txt_lName = new javax.swing.JTextField();
        sep_gender = new javax.swing.JSeparator();
        txt_emailReg = new javax.swing.JTextField();
        sep_emailReg = new javax.swing.JSeparator();
        txt_pwdReg = new javax.swing.JTextField();
        sep_pwdReg = new javax.swing.JSeparator();
        sep_cPwdReg = new javax.swing.JSeparator();
        txt_cPwdReg = new javax.swing.JTextField();
        lb_backReg = new javax.swing.JLabel();
        lb_userReg = new javax.swing.JLabel();
        lb_ageReg = new javax.swing.JLabel();
        lb_emailReg = new javax.swing.JLabel();
        lb_pwdReg = new javax.swing.JLabel();
        lb_cPwdReg = new javax.swing.JLabel();
        lb_genderReg = new javax.swing.JLabel();
        sep_pwdReg1 = new javax.swing.JSeparator();
        txt_ZipCode = new javax.swing.JTextField();
        lb_emailReg1 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        radio_male = new javax.swing.JRadioButton();
        radio_famale = new javax.swing.JRadioButton();
        lb_errorFname = new javax.swing.JLabel();
        lb_errorLname = new javax.swing.JLabel();
        lb_errorAge = new javax.swing.JLabel();
        lb_errorGender = new javax.swing.JLabel();
        lb_errorEmail = new javax.swing.JLabel();
        lb_errorZipCode = new javax.swing.JLabel();
        lb_errorPwd = new javax.swing.JLabel();
        jComboBox_Y = new javax.swing.JComboBox();
        jComboBox_M = new javax.swing.JComboBox();
        jComboBox_D = new javax.swing.JComboBox();
        lb_connection_signup = new javax.swing.JLabel();
        text_area = new javax.swing.JTextArea();
        back_reg = new javax.swing.JLabel();
        loader = new javax.swing.JPanel();
        lb_conect = new javax.swing.JLabel();
        back_loader = new javax.swing.JLabel();
        gif_earth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        pnl_bg.setBackground(new java.awt.Color(255, 255, 255));
        pnl_bg.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setPreferredSize(new java.awt.Dimension(800, 600));
        login.setLayout(null);

        txt_email.setBackground(new java.awt.Color(253, 251, 240));
        txt_email.setForeground(new java.awt.Color(102, 102, 102));
        txt_email.setText("Email");
        txt_email.setBorder(null);
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        login.add(txt_email);
        txt_email.setBounds(270, 230, 302, 24);

        txt_pwd.setBackground(new java.awt.Color(253, 251, 240));
        txt_pwd.setForeground(new java.awt.Color(102, 102, 102));
        txt_pwd.setText("jPasswordField1");
        txt_pwd.setBorder(null);
        txt_pwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pwdFocusGained(evt);
            }
        });
        login.add(txt_pwd);
        txt_pwd.setBounds(270, 320, 302, 20);

        jSeparator1.setBackground(new java.awt.Color(41, 168, 73));
        jSeparator1.setForeground(new java.awt.Color(41, 168, 73));
        login.add(jSeparator1);
        jSeparator1.setBounds(270, 260, 302, 10);

        jSeparator2.setBackground(new java.awt.Color(41, 168, 73));
        jSeparator2.setForeground(new java.awt.Color(41, 168, 73));
        jSeparator2.setToolTipText("");
        login.add(jSeparator2);
        jSeparator2.setBounds(270, 340, 302, 12);

        lb_pwdLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_pwdLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/padlock.png"))); // NOI18N
        login.add(lb_pwdLogin);
        lb_pwdLogin.setBounds(230, 310, 24, 24);

        lb_userLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_userLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/user.png"))); // NOI18N
        login.add(lb_userLogin);
        lb_userLogin.setBounds(230, 230, 24, 24);

        lb_iconLogin.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lb_iconLogin.setForeground(new java.awt.Color(102, 102, 102));
        lb_iconLogin.setText("Login");
        lb_iconLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lb_iconLoginFocusGained(evt);
            }
        });
        login.add(lb_iconLogin);
        lb_iconLogin.setBounds(350, 170, 110, 52);

        lb_signUp.setBackground(new java.awt.Color(255, 255, 255));
        lb_signUp.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lb_signUp.setText("Sign Up");
        lb_signUp.setToolTipText("");
        lb_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_signUpMouseClicked(evt);
            }
        });
        login.add(lb_signUp);
        lb_signUp.setBounds(270, 400, 43, 15);

        bt_login.setText("Login");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        login.add(bt_login);
        bt_login.setBounds(490, 390, 79, 29);

        lb_connection_login.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lb_connection_login.setText("Connection lost...");
        lb_connection_login.setForeground(Color.red);
        login.add(lb_connection_login);
        lb_connection_login.setBounds(310, 540, 220, 30);

        back_Log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/backfront.png"))); // NOI18N
        login.add(back_Log);
        back_Log.setBounds(0, 0, 800, 600);

        jPanel1.add(login, "card2");

        signUp.setBackground(new java.awt.Color(255, 255, 255));
        signUp.setPreferredSize(new java.awt.Dimension(800, 600));
        signUp.setLayout(null);

        txt_fName.setBackground(new java.awt.Color(253, 251, 240));
        txt_fName.setText("First Name");
        txt_fName.setBorder(null);
        txt_fName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fNameFocusGained(evt);
            }
        });
        txt_fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fNameActionPerformed(evt);
            }
        });
        signUp.add(txt_fName);
        txt_fName.setBounds(120, 186, 250, 20);

        sep_fName.setBackground(new java.awt.Color(41, 168, 73));
        sep_fName.setForeground(new java.awt.Color(41, 168, 73));
        sep_fName.setToolTipText("");
        signUp.add(sep_fName);
        sep_fName.setBounds(120, 210, 250, 12);

        lb_Reg.setBackground(new java.awt.Color(255, 255, 255));
        lb_Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/id-card.png"))); // NOI18N
        signUp.add(lb_Reg);
        lb_Reg.setBounds(325, 49, 128, 109);

        sep_lName.setBackground(new java.awt.Color(41, 168, 73));
        sep_lName.setForeground(new java.awt.Color(41, 168, 73));
        sep_lName.setToolTipText("");
        signUp.add(sep_lName);
        sep_lName.setBounds(492, 210, 156, 12);

        txt_lName.setBackground(new java.awt.Color(253, 251, 240));
        txt_lName.setText("Last Name");
        txt_lName.setBorder(null);
        txt_lName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lNameFocusGained(evt);
            }
        });
        signUp.add(txt_lName);
        txt_lName.setBounds(492, 184, 156, 20);

        sep_gender.setBackground(new java.awt.Color(41, 168, 73));
        sep_gender.setForeground(new java.awt.Color(41, 168, 73));
        sep_gender.setToolTipText("");
        signUp.add(sep_gender);
        sep_gender.setBounds(160, 320, 210, 12);

        txt_emailReg.setBackground(new java.awt.Color(253, 251, 240));
        txt_emailReg.setText("Email");
        txt_emailReg.setBorder(null);
        txt_emailReg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailRegFocusGained(evt);
            }
        });
        signUp.add(txt_emailReg);
        txt_emailReg.setBounds(160, 346, 210, 20);

        sep_emailReg.setBackground(new java.awt.Color(41, 168, 73));
        sep_emailReg.setForeground(new java.awt.Color(41, 168, 73));
        sep_emailReg.setToolTipText("");
        signUp.add(sep_emailReg);
        sep_emailReg.setBounds(160, 370, 210, 12);

        txt_pwdReg.setBackground(new java.awt.Color(253, 251, 240));
        txt_pwdReg.setText("Password");
        txt_pwdReg.setBorder(null);
        txt_pwdReg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pwdRegFocusGained(evt);
            }
        });
        signUp.add(txt_pwdReg);
        txt_pwdReg.setBounds(160, 446, 210, 20);

        sep_pwdReg.setBackground(new java.awt.Color(41, 168, 73));
        sep_pwdReg.setForeground(new java.awt.Color(41, 168, 73));
        sep_pwdReg.setToolTipText("");
        signUp.add(sep_pwdReg);
        sep_pwdReg.setBounds(160, 420, 210, 12);

        sep_cPwdReg.setBackground(new java.awt.Color(41, 168, 73));
        sep_cPwdReg.setForeground(new java.awt.Color(41, 168, 73));
        sep_cPwdReg.setToolTipText("");
        signUp.add(sep_cPwdReg);
        sep_cPwdReg.setBounds(160, 510, 210, 12);

        txt_cPwdReg.setBackground(new java.awt.Color(253, 251, 240));
        txt_cPwdReg.setText("Confirm Password");
        txt_cPwdReg.setBorder(null);
        txt_cPwdReg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cPwdRegFocusGained(evt);
            }
        });
        signUp.add(txt_cPwdReg);
        txt_cPwdReg.setBounds(160, 486, 210, 20);

        lb_backReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/left-arrow.png"))); // NOI18N
        lb_backReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backRegMouseClicked(evt);
            }
        });
        signUp.add(lb_backReg);
        lb_backReg.setBounds(24, 19, 24, 24);

        lb_userReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_userReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/user.png"))); // NOI18N
        signUp.add(lb_userReg);
        lb_userReg.setBounds(80, 180, 24, 24);

        lb_ageReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ageReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/birthday-cake.png"))); // NOI18N
        signUp.add(lb_ageReg);
        lb_ageReg.setBounds(120, 250, 24, 24);

        lb_emailReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_emailReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/email.png"))); // NOI18N
        signUp.add(lb_emailReg);
        lb_emailReg.setBounds(120, 340, 24, 24);

        lb_pwdReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_pwdReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/padlock2.png"))); // NOI18N
        signUp.add(lb_pwdReg);
        lb_pwdReg.setBounds(120, 440, 24, 24);

        lb_cPwdReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_cPwdReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/padlock3.png"))); // NOI18N
        signUp.add(lb_cPwdReg);
        lb_cPwdReg.setBounds(120, 480, 24, 24);

        lb_genderReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_genderReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/intersex.png"))); // NOI18N
        signUp.add(lb_genderReg);
        lb_genderReg.setBounds(120, 290, 24, 24);

        sep_pwdReg1.setBackground(new java.awt.Color(41, 168, 73));
        sep_pwdReg1.setForeground(new java.awt.Color(41, 168, 73));
        sep_pwdReg1.setToolTipText("");
        signUp.add(sep_pwdReg1);
        sep_pwdReg1.setBounds(160, 470, 210, 12);

        txt_ZipCode.setBackground(new java.awt.Color(253, 251, 240));
        txt_ZipCode.setText("Zipcode");
        txt_ZipCode.setBorder(null);
        txt_ZipCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ZipCodeFocusGained(evt);
            }
        });
        signUp.add(txt_ZipCode);
        txt_ZipCode.setBounds(160, 396, 210, 20);

        lb_emailReg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_emailReg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/gps.png"))); // NOI18N
        signUp.add(lb_emailReg1);
        lb_emailReg1.setBounds(120, 390, 24, 24);

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        signUp.add(btn_register);
        btn_register.setBounds(508, 496, 95, 29);

        grup_gender.add(radio_male);
        radio_male.setText("Male");
        signUp.add(radio_male);
        radio_male.setBounds(160, 290, 61, 23);

        grup_gender.add(radio_famale);
        radio_famale.setText("Female");
        signUp.add(radio_famale);
        radio_famale.setBounds(240, 290, 76, 23);

        lb_errorFname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_errorFname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/warning.png"))); // NOI18N
        signUp.add(lb_errorFname);
        lb_errorFname.setBounds(380, 190, 32, 30);

        lb_errorLname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_errorLname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/warning.png"))); // NOI18N
        signUp.add(lb_errorLname);
        lb_errorLname.setBounds(660, 190, 32, 32);

        lb_errorAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_errorAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/warning.png"))); // NOI18N
        signUp.add(lb_errorAge);
        lb_errorAge.setBounds(380, 250, 32, 32);

        lb_errorGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_errorGender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/warning.png"))); // NOI18N
        signUp.add(lb_errorGender);
        lb_errorGender.setBounds(380, 300, 32, 32);

        lb_errorEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_errorEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/warning.png"))); // NOI18N
        signUp.add(lb_errorEmail);
        lb_errorEmail.setBounds(380, 350, 32, 32);

        lb_errorZipCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_errorZipCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/warning.png"))); // NOI18N
        signUp.add(lb_errorZipCode);
        lb_errorZipCode.setBounds(380, 400, 32, 32);

        lb_errorPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_errorPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/warning.png"))); // NOI18N
        signUp.add(lb_errorPwd);
        lb_errorPwd.setBounds(380, 460, 32, 32);

        jComboBox_Y.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jComboBox_Y.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910" }));
        jComboBox_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_YActionPerformed(evt);
            }
        });
        signUp.add(jComboBox_Y);
        jComboBox_Y.setBounds(290, 250, 80, 27);

        jComboBox_M.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jComboBox_M.setMaximumRowCount(13);
        jComboBox_M.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MActionPerformed(evt);
            }
        });
        signUp.add(jComboBox_M);
        jComboBox_M.setBounds(150, 250, 70, 27);

        jComboBox_D.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jComboBox_D.setMaximumRowCount(32);
        jComboBox_D.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        signUp.add(jComboBox_D);
        jComboBox_D.setBounds(220, 250, 70, 27);

        lb_connection_signup.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lb_connection_signup.setText("Connection lost...");
        lb_connection_signup.setForeground(Color.red);
        signUp.add(lb_connection_signup);
        lb_connection_signup.setBounds(310, 540, 220, 30);

        text_area.setBackground(new java.awt.Color(253, 251, 240));
        text_area.setColumns(20);
        text_area.setRows(5);
        text_area.setForeground(Color.RED);
        signUp.add(text_area);
        text_area.setBounds(470, 250, 240, 240);

        back_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/background.png"))); // NOI18N
        signUp.add(back_reg);
        back_reg.setBounds(0, 0, 800, 600);

        jPanel1.add(signUp, "card4");

        loader.setBackground(new java.awt.Color(255, 255, 255));
        loader.setPreferredSize(new java.awt.Dimension(800, 600));
        loader.setLayout(null);

        lb_conect.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lb_conect.setText("Connecting to the server...");
        loader.add(lb_conect);
        lb_conect.setBounds(240, 410, 340, 30);

        back_loader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/background copy.png"))); // NOI18N
        loader.add(back_loader);
        back_loader.setBounds(0, 0, 800, 600);

        gif_earth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/earth.gif"))); // NOI18N
        loader.add(gif_earth);
        gif_earth.setBounds(120, 40, 537, 461);

        jPanel1.add(loader, "card3");

        javax.swing.GroupLayout pnl_bgLayout = new javax.swing.GroupLayout(pnl_bg);
        pnl_bg.setLayout(pnl_bgLayout);
        pnl_bgLayout.setHorizontalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_bgLayout.setVerticalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean validEmail(String email) {
        int ckemail = 0;
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";
        Connection check_email = new Connection();

        try {

            check_email.connect();
            ckemail = check_email.emailTest(email);

        } catch (Exception e) {
            System.err.println("Error email test");
        }

        Pattern pat = Pattern.compile(emailRegex);
        if (email == null) {
            text_area.append("- Email Null\n");
            return false;
        } else if (ckemail == 0) {
            text_area.append("- Email not unique\n");
            return false;
        }
        return pat.matcher(email).matches();
    }

    private boolean validZip(String zip) {
        String zipRegex = "^[0-9]{5}(?:-[0-9]{4})?$";

        Pattern pat = Pattern.compile(zipRegex);
        if (zip == null) {          
            return false;
        }
        return pat.matcher(zip).matches();
    }

    private boolean validDate(String inDate) {
        String ageRegex = "^(1[0-2]|0[1-9])/(3[01]"
                + "|[12][0-9]|0[1-9])/[0-9]{4}$";
        Pattern pattern = Pattern.compile(ageRegex);
        Matcher matcher = pattern.matcher((CharSequence) inDate);

        SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        dateFormat.setLenient(false);

        try {
            dateFormat.parse(inDate.trim());
        } catch (ParseException pe) {
            return false;
        }
        return matcher.matches();

    }

    private boolean validName(String name) {
        String nameRegex = "^[a-zA-Z\\s]{3,28}+";

        Pattern pat = Pattern.compile(nameRegex);
        if (name == null || "First Name".equals(name) || "Last Name".equals(name)) {
            text_area.append("- Name should have more than 3 letters\n and only letters.\n");
            return false;
        }
        return pat.matcher(name).matches();
    }

    private String getDate() {

        String date = null;

        if ("January".equals(jComboBox_M.getSelectedItem())) {
            date = "01";
        } else if ("February".equals(jComboBox_M.getSelectedItem())) {
            date = "02";
        } else if ("March".equals(jComboBox_M.getSelectedItem())) {
            date = "03";
        } else if ("April".equals(jComboBox_M.getSelectedItem())) {
            date = "04";
        } else if ("May".equals(jComboBox_M.getSelectedItem())) {
            date = "05";
        } else if ("June".equals(jComboBox_M.getSelectedItem())) {
            date = "06";
        } else if ("July".equals(jComboBox_M.getSelectedItem())) {
            date = "07";
        } else if ("August".equals(jComboBox_M.getSelectedItem())) {
            date = "08";
        } else if ("September".equals(jComboBox_M.getSelectedItem())) {
            date = "09";
        } else if ("October".equals(jComboBox_M.getSelectedItem())) {
            date = "10";
        } else if ("November".equals(jComboBox_M.getSelectedItem())) {
            date = "11";
        } else if ("December".equals(jComboBox_M.getSelectedItem())) {
            date = "12";
        }

        date = jComboBox_Y.getSelectedItem() + "-" + date + "-" + jComboBox_D.getSelectedItem();
        return date;
    }

    // connection test on rasberry Database
    private void testConnection() {

        Connection x = new Connection();

        lb_connection_login.setVisible(false);
        lb_connection_signup.setVisible(false);

        try {
            x.connect();
        } catch (Exception e) {
            lb_connection_login.setVisible(true);
            lb_connection_signup.setVisible(true);
            System.err.println("Erro conection test");

        }

    }

    private void cleanLogin() {
        txt_pwd.setText("Password");
        txt_email.setText("Email");
        txt_fName.setText("First Name");
        txt_lName.setText("Last Name");
        txt_emailReg.setText("Email");
        txt_pwdReg.setText("Password");
        txt_cPwdReg.setText("Confirm Password");
        txt_ZipCode.setText("ZipCode");
        grup_gender.clearSelection();
        jComboBox_D.setSelectedItem("Day");
        jComboBox_M.setSelectedItem("Month");
        jComboBox_Y.setSelectedItem("Year");
        text_area.setVisible(false);
        text_area.selectAll();
        text_area.replaceSelection("");

        //Error Icon
        lb_errorAge.setVisible(false);
        lb_errorEmail.setVisible(false);
        lb_errorFname.setVisible(false);
        lb_errorGender.setVisible(false);
        lb_errorLname.setVisible(false);
        lb_errorPwd.setVisible(false);
        lb_errorZipCode.setVisible(false);

    }
    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        String user = txt_email.getText();
        String password = String.valueOf(txt_pwd.getPassword());
        int access = 0;
        Connection loginConn = new Connection();

        try {
            access = loginConn.loginTest(user, password);

            UserID = loginConn.userId(user);

            // Save cookie 
            try (PrintWriter out = new PrintWriter("cookie.txt")) {
                out.println(UserID);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (access == 2) {

            loader.setVisible(true);
            login.setVisible(false);
            cleanLogin();

            new java.util.Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    loader.setVisible(false);

                    LocalProfile n = null;
                    try {
                        n = new LocalProfile();
                    } catch (SQLException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    n.setVisible(true);

                    dispose();
                    cleanLogin();
                }
            }, 1000 * 2);
        } else if (access == 1) {

            loader.setVisible(true);
            login.setVisible(false);
            cleanLogin();

            new java.util.Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    loader.setVisible(false);

                    UserProfile O = null;
                    try {
                        O = new UserProfile();
                    } catch (SQLException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    O.setVisible(true);

                    dispose();
                    cleanLogin();
                }
            }, 1000 * 2);
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect password or user name", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_loginActionPerformed

    private void lb_signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signUpMouseClicked
        // TODO add your handling code here:
        cleanLogin();
        login.setVisible(false);
        signUp.setVisible(true);
    }//GEN-LAST:event_lb_signUpMouseClicked
 	private void lb_iconLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lb_iconLoginFocusGained
            // TODO add your handling code here:

    }//GEN-LAST:event_lb_iconLoginFocusGained
     private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
         // TODO add your handling code here:
         if ("Email".equals(txt_email.getText())) {
             txt_email.setText("");
         }
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_pwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pwdFocusGained
        // TODO add your handling code here:
        txt_pwd.setText("");
    }//GEN-LAST:event_txt_pwdFocusGained

    private void txt_fNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fNameFocusGained
        // TODO add your handling code here:
        if ("First Name".equals(txt_fName.getText())) {
            txt_fName.setText("");
        }

    }//GEN-LAST:event_txt_fNameFocusGained

    private void txt_lNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lNameFocusGained
        // TODO add your handling code here:
        if ("Last Name".equals(txt_lName.getText())) {
            txt_lName.setText("");
        }

    }//GEN-LAST:event_txt_lNameFocusGained

    private void txt_emailRegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailRegFocusGained
        if ("Email".equals(txt_emailReg.getText())) {
            txt_emailReg.setText("");
        }

    }//GEN-LAST:event_txt_emailRegFocusGained

    private void txt_pwdRegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pwdRegFocusGained
        txt_pwdReg.setText("");
    }//GEN-LAST:event_txt_pwdRegFocusGained

    private void txt_cPwdRegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cPwdRegFocusGained
        txt_cPwdReg.setText("");
    }//GEN-LAST:event_txt_cPwdRegFocusGained

    private void txt_ZipCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ZipCodeFocusGained
        // TODO add your handling code here:
        txt_ZipCode.setText("");

    }//GEN-LAST:event_txt_ZipCodeFocusGained

    private void lb_backRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backRegMouseClicked
        // TODO add your handling code here:
        cleanLogin();
        signUp.setVisible(false);
        login.setVisible(true);

    }//GEN-LAST:event_lb_backRegMouseClicked

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
       // Check = 1 means there is some error... 
        // Check = 0 means pass on check list 
        int check = 0;

        // Clean error section
        text_area.selectAll();
        text_area.replaceSelection("");

        // check if email is correct
        if (validEmail(txt_emailReg.getText())) {
            lb_errorEmail.setVisible(false);
        } else {
            lb_errorEmail.setVisible(true);
            text_area.append("- Email Error.\n");
            check = 1;
        }
        // check if Zipcode is correct
        if (validZip(txt_ZipCode.getText())) {
            lb_errorZipCode.setVisible(false);
        } else {
            lb_errorZipCode.setVisible(true);
            text_area.append("- Zipcode should have 5 numbers. \n");
            check = 1;
        }
        // check if Birthday's date is correct
        if (("Day".equals(jComboBox_D.getSelectedItem()) || "Month".equals(jComboBox_M.getSelectedItem()) || "Year".equals(jComboBox_Y.getSelectedItem()) && validDate(getDate()))) {
            text_area.append("- Birthday is blank.\n");
            lb_errorAge.setVisible(true);
            check = 1;
        } else {
            lb_errorAge.setVisible(false);
        }

        if (validName(txt_fName.getText())) {
            lb_errorFname.setVisible(false);
        } else {
            lb_errorFname.setVisible(true);
            check = 1;
        }

        if (validName(txt_lName.getText())) {
            lb_errorLname.setVisible(false);
        } else {
            lb_errorLname.setVisible(true);
            check = 1;
        }

        if (grup_gender.getSelection() != null) {
            lb_errorGender.setVisible(false);
        } else {
            lb_errorGender.setVisible(true);
            text_area.append("- Gender is blank.\n");
            check = 1;
        }
        if (txt_pwdReg.getText().equals(txt_cPwdReg.getText())) {
            lb_errorPwd.setVisible(false);
        } else {
            lb_errorPwd.setVisible(true);
            text_area.append("- Password does not match.\n");
            check = 1;
        }
        if (check == 0) {
            JOptionPane.showMessageDialog(null, "User is saved successfully in database", "", JOptionPane.PLAIN_MESSAGE);

            char gen;
            if (radio_famale.isSelected()) {
                gen = 'F';
            } else {
                gen = 'M';
            }

            Connection sign = new Connection();
            sign.connect();
            String sqlAdd = "INSERT INTO locals_person(firstname,lastname,email,pwd,gender,zipcode, dateBirth) "
                    + "VALUES ('" + txt_fName.getText() + "','" + txt_lName.getText() + "', '" + txt_emailReg.getText() + "', '" + txt_pwdReg.getText() + "','" + gen + "'," + txt_ZipCode.getText() + ",'" + getDate() + "')";

            try {
                sign.query(sqlAdd);
                System.out.println("Successfully saved in database...");
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println("Erro to Saved");
            }
            // go back to login  
            cleanLogin();
            signUp.setVisible(false);
            login.setVisible(true);
        } else {

            text_area.setVisible(true);
            JOptionPane.showMessageDialog(null, "Error, try again!!", "Erro", JOptionPane.WARNING_MESSAGE);

        }


      }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void jComboBox_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_YActionPerformed

    private void jComboBox_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MActionPerformed

    private void txt_fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Home().setVisible(true);

            }

        });
    }
    private void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_Log;
    private javax.swing.JLabel back_loader;
    private javax.swing.JLabel back_reg;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel gif_earth;
    private javax.swing.ButtonGroup grup_gender;
    private javax.swing.JComboBox jComboBox_D;
    private javax.swing.JComboBox jComboBox_M;
    private javax.swing.JComboBox jComboBox_Y;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_Reg;
    private javax.swing.JLabel lb_ageReg;
    private javax.swing.JLabel lb_backReg;
    private javax.swing.JLabel lb_cPwdReg;
    private javax.swing.JLabel lb_conect;
    private javax.swing.JLabel lb_connection_login;
    private javax.swing.JLabel lb_connection_signup;
    private javax.swing.JLabel lb_emailReg;
    private javax.swing.JLabel lb_emailReg1;
    private javax.swing.JLabel lb_errorAge;
    private javax.swing.JLabel lb_errorEmail;
    private javax.swing.JLabel lb_errorFname;
    private javax.swing.JLabel lb_errorGender;
    private javax.swing.JLabel lb_errorLname;
    private javax.swing.JLabel lb_errorPwd;
    private javax.swing.JLabel lb_errorZipCode;
    private javax.swing.JLabel lb_genderReg;
    private javax.swing.JLabel lb_iconLogin;
    private javax.swing.JLabel lb_pwdLogin;
    private javax.swing.JLabel lb_pwdReg;
    private javax.swing.JLabel lb_signUp;
    private javax.swing.JLabel lb_userLogin;
    private javax.swing.JLabel lb_userReg;
    private javax.swing.JPanel loader;
    private javax.swing.JPanel login;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JRadioButton radio_famale;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JSeparator sep_cPwdReg;
    private javax.swing.JSeparator sep_emailReg;
    private javax.swing.JSeparator sep_fName;
    private javax.swing.JSeparator sep_gender;
    private javax.swing.JSeparator sep_lName;
    private javax.swing.JSeparator sep_pwdReg;
    private javax.swing.JSeparator sep_pwdReg1;
    private javax.swing.JPanel signUp;
    private javax.swing.JTextArea text_area;
    private javax.swing.JTextField txt_ZipCode;
    private javax.swing.JTextField txt_cPwdReg;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailReg;
    private javax.swing.JTextField txt_fName;
    private javax.swing.JTextField txt_lName;
    private javax.swing.JPasswordField txt_pwd;
    private javax.swing.JTextField txt_pwdReg;
    // End of variables declaration//GEN-END:variables
}
