/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernandobrambillademello
 */
public final class LocalProfile extends javax.swing.JFrame {
    home.Connection x = new home.Connection();
    public String type = "";
    public int userInfo;

    
    public LocalProfile() throws SQLException {
        initComponents();
            getID();
        clearTable();
        show_locals();
   
        messageWelcome();
    }
     
    
//get Info from txt
    public void getID() {
        try {

            BufferedReader br = new BufferedReader(new FileReader("cookie.txt"));
            String strLine;
            //Read File Line By Line
            while ((strLine = br.readLine()) != null) {
                // Print the content on the console
                userInfo = Integer.parseInt(strLine);
            }
        } catch (IOException | NumberFormatException e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        } finally {

        }
    }
    public void messageWelcome() throws SQLException{
        String first;
        String last;
        first = x.genericPerson("firstname", "person_id" , Integer.toString(userInfo) );
        last = x.genericPerson("lastname", "person_id" , Integer.toString(userInfo) );
        lb_nameUser.setText("Welcome Local User "+ first + " " +last + " to Locals App."  );
        
    }

    public void clearTable() {
        DefaultTableModel dm = (DefaultTableModel) local_Display.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }
        jEventLocation.setText("");
        jComboBox_D.setSelectedItem("Day");
        jComboBox_M.setSelectedItem("Month");
        jCombo_hour.setSelectedItem("00");
        jComboBox_M.setSelectedItem("00");
    }

   

    public ArrayList<Localusers> localsFeed(String SQL) throws SQLException {
        ArrayList<Localusers> localsFeed = new ArrayList<>();
        java.sql.Connection conn = null;
        Statement stmt = null;
        conn = DriverManager.getConnection("jdbc:mysql://45.49.254.49:3306/locals", "root", "toor");
        try {
            stmt = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Localusers lu;
        try (ResultSet rs = stmt.executeQuery(SQL)) {
            if (rs.next() == false) {
                System.out.println("ResultSet in empty in Java");

            } else {
                do {
                    lu = new Localusers(rs.getInt("act_code"), rs.getString("act_type"), rs.getString("act_date"), rs.getString("act_time"), rs.getString("act_location"), rs.getString("firstname"));
                    localsFeed.add(lu);
                } while (rs.next());
            }
        } catch (Exception e) {
            System.err.println("error");
            JOptionPane.showMessageDialog(null, e);

        }
        return localsFeed;
    }



    public void show_locals() throws SQLException {
        String queryActivity ="select * \n" +
                    "from locals_person P\n" +
                    "Join locals_act A \n" +
                    "on P.person_id = A.act_creator and P.person_id= "+ userInfo +" ";
        
        ArrayList<Localusers> list = localsFeed(queryActivity);
        DefaultTableModel model = (DefaultTableModel) local_Display.getModel();
        Object[] row = new Object[1000];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getCodeAct();
            row[1] = list.get(i).getActType();
            row[2] = list.get(i).getDay();
            row[3] = list.get(i).getTime();
            row[4] = list.get(i).getLocation();
            row[5] = list.get(i).getFirstname();
            model.addRow(row);

        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pTurist = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        bt_becameTurist = new javax.swing.JButton();
        messages = new javax.swing.JButton();
        beALocal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        local_Display = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lb_nameUser = new javax.swing.JLabel();
        update1 = new javax.swing.JButton();
        lb_back = new javax.swing.JLabel();
        pActivityManeger = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jB_deleteLocal = new javax.swing.JButton();
        jB_addLocal = new javax.swing.JButton();
        jCombo_type1 = new javax.swing.JComboBox<String>();
        JText_delete_field = new javax.swing.JTextField();
        jComboBox_M = new javax.swing.JComboBox();
        jComboBox_D = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jEventLocation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCombo_hour = new javax.swing.JComboBox();
        jCombo_minute = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jActivityDescri = new javax.swing.JTextArea();
        back_ground = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        pTurist.setBackground(new java.awt.Color(255, 255, 255));
        pTurist.setPreferredSize(new java.awt.Dimension(800, 600));
        pTurist.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/logo.png"))); // NOI18N
        pTurist.add(jLabel1);
        jLabel1.setBounds(40, 80, 190, 190);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        pTurist.add(logout);
        logout.setBounds(10, 510, 250, 53);

        bt_becameTurist.setText("Become a Tourist");
        bt_becameTurist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_becameTuristActionPerformed(evt);
            }
        });
        pTurist.add(bt_becameTurist);
        bt_becameTurist.setBounds(640, 20, 140, 40);

        messages.setText("Messages");
        messages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagesActionPerformed(evt);
            }
        });
        pTurist.add(messages);
        messages.setBounds(10, 370, 250, 53);

        beALocal.setText("Activity Manager");
        beALocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beALocalActionPerformed(evt);
            }
        });
        pTurist.add(beALocal);
        beALocal.setBounds(10, 440, 250, 53);

        local_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Activity code", "Type", "Day", "Time", "Location", "Creator"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        local_Display.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(local_Display);

        pTurist.add(jScrollPane1);
        jScrollPane1.setBounds(270, 100, 520, 460);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Your Activities");
        pTurist.add(jLabel3);
        jLabel3.setBounds(450, 60, 240, 30);

        lb_nameUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lb_nameUser.setText("msg");
        pTurist.add(lb_nameUser);
        lb_nameUser.setBounds(10, 20, 430, 20);

        update1.setText("Reload");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        pTurist.add(update1);
        update1.setBounds(10, 290, 250, 53);

        lb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/background.png"))); // NOI18N
        pTurist.add(lb_back);
        lb_back.setBounds(0, 0, 800, 600);

        getContentPane().add(pTurist, "card2");

        pActivityManeger.setBackground(new java.awt.Color(255, 255, 255));
        pActivityManeger.setPreferredSize(new java.awt.Dimension(800, 600));
        pActivityManeger.setLayout(null);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        pActivityManeger.add(backBtn);
        backBtn.setBounds(6, 6, 75, 29);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Activity Manager ");
        pActivityManeger.add(jLabel2);
        jLabel2.setBounds(150, 60, 495, 55);

        jB_deleteLocal.setText("Delete");
        jB_deleteLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_deleteLocalActionPerformed(evt);
            }
        });
        pActivityManeger.add(jB_deleteLocal);
        jB_deleteLocal.setBounds(590, 480, 97, 29);

        jB_addLocal.setText("Create Activity");
        jB_addLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addLocalActionPerformed(evt);
            }
        });
        pActivityManeger.add(jB_addLocal);
        jB_addLocal.setBounds(580, 350, 130, 29);

        jCombo_type1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Surfing", "Snowboarding", "Hiking", "Fishing ", "Sailing", "Cycling", "Skiing", "Rock Climbing", "Camping", "Skateboarding", "City Tours ", "Art", "Museums", "Restaurants ", "Nightlife " }));
        pActivityManeger.add(jCombo_type1);
        jCombo_type1.setBounds(60, 210, 240, 27);
        pActivityManeger.add(JText_delete_field);
        JText_delete_field.setBounds(600, 440, 80, 28);

        jComboBox_M.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jComboBox_M.setMaximumRowCount(13);
        jComboBox_M.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        pActivityManeger.add(jComboBox_M);
        jComboBox_M.setBounds(560, 220, 90, 27);

        jComboBox_D.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jComboBox_D.setMaximumRowCount(32);
        jComboBox_D.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        pActivityManeger.add(jComboBox_D);
        jComboBox_D.setBounds(650, 220, 70, 27);

        jLabel4.setBackground(new java.awt.Color(102, 153, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText(" Activity Description");
        pActivityManeger.add(jLabel4);
        jLabel4.setBounds(110, 270, 140, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Event Time");
        pActivityManeger.add(jLabel5);
        jLabel5.setBounds(470, 250, 90, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Enter code of your Activity to delete");
        pActivityManeger.add(jLabel6);
        jLabel6.setBounds(520, 410, 250, 17);
        pActivityManeger.add(jEventLocation);
        jEventLocation.setBounds(550, 310, 190, 28);

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText(" Activity Type:");
        pActivityManeger.add(jLabel7);
        jLabel7.setBounds(120, 180, 130, 30);

        jCombo_hour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        pActivityManeger.add(jCombo_hour);
        jCombo_hour.setBounds(580, 250, 70, 27);

        jCombo_minute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        pActivityManeger.add(jCombo_minute);
        jCombo_minute.setBounds(650, 250, 70, 27);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Event Location");
        pActivityManeger.add(jLabel9);
        jLabel9.setBounds(590, 290, 120, 17);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Event Date");
        pActivityManeger.add(jLabel8);
        jLabel8.setBounds(472, 215, 90, 30);

        jActivityDescri.setColumns(20);
        jActivityDescri.setRows(5);
        jScrollPane2.setViewportView(jActivityDescri);

        pActivityManeger.add(jScrollPane2);
        jScrollPane2.setBounds(60, 310, 244, 140);

        back_ground.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        back_ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Img/background.png"))); // NOI18N
        pActivityManeger.add(back_ground);
        back_ground.setBounds(0, 0, 800, 600);

        getContentPane().add(pActivityManeger, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:

        Home n = new Home();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void bt_becameTuristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_becameTuristActionPerformed
int op = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to become a tourist?\n "
           +"You can only go back to the local profile by logging out",
            " ",
            JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION)
{
                     UserProfile n = null;
                    try {
                        n = new UserProfile();
                    } catch (SQLException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    n.setVisible(true);
                    dispose();     
}


        
        
            
        
    }//GEN-LAST:event_bt_becameTuristActionPerformed

    private void beALocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beALocalActionPerformed
        // TODO add your handling code here:
        pActivityManeger.setVisible(true);
        pTurist.setVisible(false);
    }//GEN-LAST:event_beALocalActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        clearTable();
        try {
            show_locals();

        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }

        pActivityManeger.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed
        private String getTime(){
            String time = null;
            
            time = (String) jCombo_hour.getSelectedItem() + (String) jCombo_hour.getSelectedItem();
            return time;
        }
        private String getDate() { 
        String date= null;

        String thisMonth = new SimpleDateFormat("MM").format(new Date());
        String thisYear = new SimpleDateFormat("yyyy").format(new Date());
        int thisM, monthInput, year = 0;
        
        System.out.println(thisMonth);  
        
        home.Tools y = new Tools();
        date = y.convertData((String)jComboBox_M.getSelectedItem());
              
        thisM = Integer.parseInt(thisMonth);
        monthInput = Integer.parseInt(date);
        year = Integer.parseInt(thisYear);
        
            System.out.println(year + " " + thisM);    
        if(monthInput < thisM ){
            year++; 
        }
        System.out.println(year + " " + monthInput); 
        
        

        date = year + "-" + date + "-" + jComboBox_D.getSelectedItem();
        return date;
    }
    private void jB_deleteLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_deleteLocalActionPerformed
try {
            if (x.activityCheckExistOwner(JText_delete_field.getText() , userInfo) == 1){
                
                String sqlAdd = "delete from locals_act where act_code = " + JText_delete_field.getText() +" ";
                       
                x.query(sqlAdd);
                JOptionPane.showMessageDialog(null, "Activity " + JText_delete_field.getText() + " was deleted successfully", "", JOptionPane.PLAIN_MESSAGE);
            }else{
                System.err.print("Error Activity deleted");
                JOptionPane.showMessageDialog(null, "Something wrong!!, try again!!", "Erro", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Something wrong!!, try again!!", "Erro", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
            
        }     
    }//GEN-LAST:event_jB_deleteLocalActionPerformed

    private void jB_addLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addLocalActionPerformed
        Connection newAc = new Connection();
            newAc.connect();
            String sqlAdd = "INSERT INTO locals_act(act_type,act_location,act_descri,act_date,act_time, act_creator) "
                    + "VALUES ('" + jCombo_type1.getSelectedItem() + "','"+ jEventLocation.getText() + "','" + jActivityDescri.getText() + "','" + getDate()+ "','" + getTime() + "','" + userInfo +  "')";

            try {
                newAc.query(sqlAdd);
                System.out.println("Successfully saved in database...");
                    JOptionPane.showMessageDialog(null, "Activity was successfully added", "", JOptionPane.PLAIN_MESSAGE);
                clearTable();
               try {
               show_locals();

                } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
               }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something wrong!!, try again!!", "Erro", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);               
                System.err.println("Erro to Saved");
            }
    }//GEN-LAST:event_jB_addLocalActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void messagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagesActionPerformed
        System.out.println("Messages go here");
        JFrame chatWindow = new MessagingClient(userInfo);
        chatWindow.setVisible(true);
      //              dispose();     
    }//GEN-LAST:event_messagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LocalProfile().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LocalProfile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JText_delete_field;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel back_ground;
    private javax.swing.JButton beALocal;
    private javax.swing.JButton bt_becameTurist;
    private javax.swing.JTextArea jActivityDescri;
    private javax.swing.JButton jB_addLocal;
    private javax.swing.JButton jB_deleteLocal;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox_D;
    private javax.swing.JComboBox jComboBox_M;
    private javax.swing.JComboBox jCombo_hour;
    private javax.swing.JComboBox jCombo_minute;
    private javax.swing.JComboBox<String> jCombo_type1;
    private javax.swing.JTextField jEventLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_back;
    private javax.swing.JLabel lb_nameUser;
    private javax.swing.JTable local_Display;
    private javax.swing.JButton logout;
    private javax.swing.JButton messages;
    private javax.swing.JPanel pActivityManeger;
    private javax.swing.JPanel pTurist;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
